<a href="https://colab.research.google.com/github/pradiptars/Ml_tensorflow_model2/blob/main/Untitled43.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [9]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [10]:
from google.colab import files
uploaded = files.upload()

Saving Churn_Modelling (1).csv to Churn_Modelling (1) (1).csv

In [11]:
df = pd.read_csv('Churn_Modelling (1).csv')

In [12]:
df.head(2)

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0

In [13]:
df.drop('Surname', axis=1, inplace=True)

In [14]:
df.dtypes

RowNumber            int64
CustomerId           int64
CreditScore          int64
Geography           object
Gender              object
Age                  int64
Tenure               int64
Balance            float64
NumOfProducts        int64
HasCrCard            int64
IsActiveMember       int64
EstimatedSalary    float64
Exited               int64
dtype: object

In [16]:
df['Geography'].value_counts()

Geography
France     5014
Germany    2509
Spain      2477
Name: count, dtype: int64

In [17]:
def print_unique_col_values(df):
  for columns in df:
    if df[columns].dtypes == 'object':
      print(f"{columns}: {df[columns].unique()}")

In [18]:
print_unique_col_values(df)

Geography: ['France' 'Spain' 'Germany']
Gender: ['Female' 'Male']

In [19]:
df['Gender'].replace({'Female': 1, 'Male': 0}, inplace=True)

/tmp/ipython-input-3198137745.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Gender'].replace({'Female': 1, 'Male': 0}, inplace=True)
/tmp/ipython-input-3198137745.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['Gender'].replace({'Female': 1, 'Male': 0}, inplace=True)

In [20]:
df.head(2)

,RowNumber,CustomerId,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,619,France,1,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,608,Spain,1,41,1,83807.86,1,0,1,112542.58,0

In [21]:
df1 = pd.get_dummies(df, columns=['Geography'], dtype='int64')

In [22]:
df1.head(2)

,RowNumber,CustomerId,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,1,15634602,619,1,42,2,0.00,1,1,1,101348.88,1,1,0,0
1,2,15647311,608,1,41,1,83807.86,1,0,1,112542.58,0,0,0,1

In [24]:
df1.dtypes

RowNumber              int64
CustomerId             int64
CreditScore            int64
Gender                 int64
Age                    int64
Tenure                 int64
Balance              float64
NumOfProducts          int64
HasCrCard              int64
IsActiveMember         int64
EstimatedSalary      float64
Exited                 int64
Geography_France       int64
Geography_Germany      int64
Geography_Spain        int64
dtype: object

In [33]:
col_for_scale = ['CustomerId', 'CreditScore', 'Age', 'Balance', 'EstimatedSalary' ]

In [34]:
from sklearn.preprocessing import MinMaxScaler
sc = MinMaxScaler()
df1[col_for_scale] = sc.fit_transform(df1[col_for_scale])

In [35]:
df1.head(2)

,RowNumber,CustomerId,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,1,0.275616,0.538,1,0.324324,2,0.000000,1,1,1,0.506735,1,1,0,0
1,2,0.326454,0.516,1,0.310811,1,0.334031,1,0,1,0.562709,0,0,0,1

In [36]:
for col in df1:
  print(f'{col}: {df1[col].unique()}')

RowNumber: [    1     2     3 ...  9998  9999 10000]
CustomerId: [0.27561613 0.32645436 0.21442143 ... 0.07532731 0.46663653 0.25048302]
CreditScore: [0.538 0.516 0.304 0.698 1.    0.59  0.944 0.052 0.302 0.668 0.356 0.294
 0.252 0.398 0.57  0.532 0.606 0.474 0.752 0.764 0.572 0.32  0.638 0.992
 0.454 0.812 0.442 0.448 0.122 0.482 0.366 0.406 0.34  0.744 0.25  0.28
 0.908 0.464 0.244 0.23  0.412 0.968 0.62  0.852 0.958 0.574 0.4   0.696
 0.47  0.876 0.61  0.502 0.612 0.75  0.322 0.528 0.784 0.674 0.41  0.506
 0.802 0.462 0.77  0.622 0.65  0.776 0.926 0.614 0.508 0.338 0.628 0.656
 0.814 0.132 0.63  0.854 0.386 0.312 0.286 0.604 0.8   0.758 0.592 0.594
 0.916 0.348 0.838 0.76  0.33  0.846 0.928 0.72  0.126 0.546 0.64  0.544
 0.87  0.51  0.258 0.67  0.376 0.424 0.742 0.556 0.636 0.956 0.648 0.55
 0.164 0.84  0.816 0.89  0.672 0.878 0.478 0.222 0.468 0.458 0.626 0.664
 0.886 0.682 0.27  0.6   0.808 0.37  0.732 0.378 0.712 0.472 0.562 0.734
 0.9   0.666 0.708 0.53  0.634 0.268 0.26  0.456 0.324 0.512 0.494 0.856
 0.328 0.35  0.73  0.46  0.914 0.342 0.818 0.332 0.722 0.536 0.586 0.642
 0.678 0.54  0.652 0.444 0.69  0.484 0.434 0.688 0.394 0.488 0.646 0.52
 0.834 0.826 0.724 0.706 0.624 0.618 0.346 0.844 0.39  0.568 0.778 0.842
 0.662 0.388 0.692 0.832 0.754 0.686 0.414 0.362 0.296 0.602 0.882 0.766
 0.922 0.714 0.728 0.864 0.85  0.898 0.504 0.788 0.476 0.794 0.466 0.554
 0.762 0.558 0.176 0.584 0.912 0.248 0.418 0.158 0.66  0.798 0.768 0.588
 0.552 0.598 0.91  0.736 0.98  0.56  0.608 0.824 0.436 0.526 0.344 0.774
 0.596 0.186 0.58  0.38  0.22  0.486 0.902 0.522 0.904 0.79  0.266 0.68
 0.284 0.718 0.71  0.42  0.804 0.702 0.374 0.274 0.492 0.704 0.272 0.748
 0.396 0.228 0.88  0.368 0.796 0.288 0.48  0.236 0.318 0.936 0.932 0.372
 0.806 0.848 0.542 0.438 0.616 0.896 0.582 0.384 0.684 0.578 0.83  0.44
 0.576 0.498 0.564 0.858 0.354 0.428 0.966 0.308 0.984 0.316 0.134 0.496
 0.782 0.514 0.822 0.996 0.392 0.178 0.81  0.82  0.352 0.726 0.7   0.632
 0.432 0.29  0.676 0.524 0.254 0.154 0.978 0.938 0.74  0.218 0.306 0.548
 0.358 0.426 0.264 0.892 0.19  0.792 0.872 0.408 0.644 0.874 0.298 0.988
 0.2   0.93  0.976 0.906 0.772 0.566 0.5   0.658 0.334 0.884 0.786 0.276
 0.142 0.982 0.716 0.314 0.31  0.212 0.17  0.422 0.336 0.43  0.756 0.868
 0.404 0.518 0.828 0.694 0.746 0.402 0.188 0.738 0.292 0.382 0.96  0.924
 0.654 0.14  0.49  0.534 0.918 0.3   0.952 0.168 0.326 0.256 0.894 0.026
 0.098 0.226 0.86  0.204 0.45  0.974 0.888 0.948 0.156 0.946 0.862 0.998
 0.278 0.162 0.214 0.836 0.962 0.018 0.94  0.446 0.452 0.416 0.934 0.198
 0.18  0.13  0.942 0.36  0.    0.192 0.15  0.78  0.262 0.866 0.016 0.99
 0.202 0.216 0.238 0.146 0.108 0.972 0.246 0.97  0.232 0.282 0.002 0.954
 0.986 0.03  0.364 0.128 0.206 0.242 0.102 0.92  0.964 0.24  0.194 0.144
 0.95  0.16  0.172 0.152 0.116 0.994 0.136 0.174 0.12  0.208 0.114 0.21
 0.224 0.072 0.11  0.066 0.09  0.234 0.166 0.184 0.148 0.196 0.182 0.034
 0.124 0.064 0.046 0.138]
Gender: [1 0]
Age: [0.32432432 0.31081081 0.28378378 0.33783784 0.35135135 0.43243243
 0.14864865 0.12162162 0.17567568 0.08108108 0.21621622 0.09459459
 0.22972973 0.36486486 0.54054054 0.18918919 0.27027027 0.37837838
 0.24324324 0.2027027  0.2972973  0.44594595 0.58108108 0.41891892
 0.25675676 0.01351351 0.64864865 0.51351351 0.10810811 0.04054054
 0.5        0.77027027 0.05405405 0.16216216 0.13513514 0.63513514
 0.40540541 0.45945946 0.52702703 0.74324324 0.39189189 0.48648649
 0.72972973 0.02702703 0.66216216 0.82432432 0.59459459 0.47297297
 0.83783784 0.55405405 0.67567568 0.06756757 0.56756757 0.7027027
 0.60810811 0.62162162 0.         0.86486486 0.68918919 0.75675676
 0.71621622 0.78378378 0.7972973  0.94594595 0.90540541 0.89189189
 0.81081081 0.85135135 1.         0.87837838]
Tenure: [ 2  1  8  7  4  6  3 10  5  9  0]
Balance: [0.         0.33403148 0.63635718 ... 0.22865702 0.29922631 0.51870777]
NumOfProducts: [1 3 2 4]
HasCrCard: [1 0]
IsActiveMember: [1 0]
EstimatedSalary: [0.50673489 0.56270874 0.56965435 ... 0.21039009 0.46442905 0.19091423]
Exited: [1 0]
Geography_France: [1 0]
Geography_Germany: [0 1]
Geography_Spain: [0 1]

In [37]:
X = df1.drop('Exited', axis=1)
y = df1['Exited']

In [38]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=5)

In [39]:
len(X_train.columns)

14

In [40]:
import tensorflow as tf
from tensorflow import keras

In [42]:

model = keras.Sequential([
    keras.layers.Dense(26, input_shape=(14,), activation='relu'),
    keras.layers.Dense(15, activation='relu'),
    keras.layers.Dense(1, activation='sigmoid')
])
model.compile(optimizer='adam',
              loss='binary_crossentropy',
              metrics=['accuracy'])
model.fit(X_train, y_train, epochs=5)

Epoch 1/5

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.5454 - loss: 217.8526
Epoch 2/5
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7089 - loss: 1.7065
Epoch 3/5
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.6948 - loss: 1.3668
Epoch 4/5
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7006 - loss: 2.5543
Epoch 5/5
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7173 - loss: 1.8457

In [43]:
model.evaluate(X_test, y_test)

63/63 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.7971 - loss: 1.0443

[1.0562875270843506, 0.7954999804496765]

In [44]:
yp = model.predict(X_test)
yp[:5]

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step

array([[0.00042106],
       [0.15248397],
       [0.00576549],
       [0.03559529],
       [0.02379131]], dtype=float32)

In [45]:
y_test[:5]

7054    0
442     0
3954    0
2288    0
3196    0
Name: Exited, dtype: int64

In [46]:
y_pred = []
for elements in yp:
  if elements > 0.5:
    y_pred.append(1)
  else:
    y_pred.append(0)

In [47]:
y_pred[:5]

[0, 0, 0, 0, 0]